export enum EnvironmentVariables {
  APP_PORT = 'APP_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  SEED_USER_MAIL = 'SEED_USER_MAIL',
  SEED_USER_PASSWORD = 'SEED_USER_PASSWORD',
  SEED_USER_NAME = 'SEED_USER_NAME',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET'
}
